### PR TITLE
Integrate Firebase

### LINKED ISSUE #7: Firebase Integration
1. A Firebase project for Instreal should be created.
2. The Flutter project is connected to the Firebase project.

### PR DESCRIPTION
**Pull request by leehack**
Firebase Integration

1. Firebase configuration is done with flutterfire command.
2. Readme file for Firebase integration added.

Closes #7

### CODE REVIEW

**Comment by aliyazdi75** [comment]
I think google service and other stuff like app id should be secret in github. Otherwise, anyone can access to our firebase.

**Comment by leehack** [comment]
> I think google service and other stuff like app id should be secret in github. Otherwise, anyone can access to our firebase.

As far as I know, they aren't secrets. What we need to do is put the disallow rule by default.

**Comment by leehack** [comment]
> > > I think google service and other stuff like app id should be secret in github. Otherwise, anyone can access to our firebase.
> > 
> > 
> > As far as I know, they aren't secrets. What we need to do is put the disallow rule by default.
> 
> As far as I know, it's not safe to check it into public git. If you see flutter repos, none of them check them into the git like: [flutter/gallery@`main`/.gitignore#L80](https://github.com/flutter/gallery/blob/main/.gitignore?rgh-link-date=2023-06-27T15%3A01%3A58Z#L80)

It's a bit out dated but read this: https://groups.google.com/g/firebase-talk/c/bamCgTDajkw

It's normal it's quite often in gitignore for open source examples because they don't want users just copy-paste the json files but the json file itself isn't a secret. It's basically public no matter web/mobile/desktop since they can be just extracted from APK for Android for example.

We can put this in an environment variable for github action but I don't think it is worths it.

**Review by aliyazdi75 — APPROVED** [review]
@leehack Ok, but did you bind it with the keys?

**Comment by leehack** [comment]
@aliyazdi75 Which key do you mean? Bind to what? Firebase project?

**Comment by aliyazdi75** [comment]
> @aliyazdi75 Which key do you mean? Bind to what? Firebase project?

Yes, `jks` key and `key.properties`, otherwise the project is exposed to be used by the other ppl :)

**Comment by leehack** [comment]
@aliyazdi75 ah, you mean the signing keys. Probably my debug signing key should be registered in the Firebase console but I didn't even create a release key. We can tackle that when we build CI/CD later.

**Comment by aliyazdi75** [comment]
This is the section when you build sha key:
image

**Comment by leehack** [comment]
@aliyazdi75 Yep. I know. But it's only for Android. What we are supposed to do is put the security rule and app check if we want to make it secure. The fingerprint doesn't protect our backend.

**Pull request merged**
